### PR TITLE
Addition of `API` documentation

### PR DESCRIPTION
**Pull request by Zshan0**
Pyqrack currently does not have any documentation, after the initial commit, this PR is to add some basic documentation along with the `API` section similar to the one present in [qrack](https://qrack.readthedocs.io/en/latest/index.html). As more of the documentation is added, it can be finalized with discussions with the community on this PR

### CODE REVIEW

**Comment by Zshan0** [comment]
So I have started with single & multi-gates as of now, I had a few doubts that will help me complete them.
Where can I find the description or usage of the following functions? 
- `adji`
- `adjs`
-  `adji`
-  `multiplex1_mtrx`

Also, I'm not clear on what the parameters represent for the following gates:

- `exp`
- `mtrx`
- `u` (unitary gate)
- `r`
It would be great if there is more context for the `fsim` gate in both pyqrack & qrack documentation, it is not a well-known gate imo

**Comment by WrathfulSpatula** [comment]
You're doing well, and feel free to ask me more!

(The `adj` prefix indicates "adjoint," or "inverse," first of all.)

- `adji` is not a gate. You probably saw `adjiswap`, which is the "adjoint" (`adj`) of `iswap`, which is a SWAP gate that applies a phase factor of (imaginary) `i` if the bits being swapped have different logical values. So, this is "adjoint" of "ISWAP," which "uncomputes" or "undoes" "ISWAP." (Therefore, this turns out to be an "ISWAP"-like gate that applies `-i` as a phase factor if the swapped bits are different, as opposed to positive `i`.)
- `adjs` is the "adjoint of S gate." S gate applies a phase factor of `i` to the |1> state of a bit, only, so "adjoint S" applies `-i` to |1>, only.
- `multiplex1_mtrx` a "multiplex" with an arbitrarily large number of controls and a single target bit. This is related to "uniformly controlled gates," like explained in [this article on arXiv](https://arxiv.org/pdf/quant-ph/0410066.pdf). I originally got the idea from ProjectQ (by Steiger and others). Don't worry too much about this gate, except for your own interest; it's sufficient to describe it as "a multiplex gate with a single target and an arbitrary number of controls," or to that basic effect.

As for your list of ambiguous parameters...

- `exp` is a compatibility gate for the Microsoft QDK. It "applies the exponential of a multi-qubit operator." The best explanation I can point you to is in [their documentation](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.exp), (with thanks). `b` is the list of Pauli bases, and `th` is "theta."
- `mtrx` is a specify-your-own-2x2-1qb-matrx-operation gate. `m` is the 2x2 complex number operator, but in a row-major flattened list of complex components. `q` is the qubit index to which to apply the gate.
- `u` is a 3-parameter unitary gate, as explained in [the Qiskit docs](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html). `q` is the qubit index to which to apply the gate. and `th, ph, la` are "theta, phi lambda," per Qiskit's convention.
- `r` is a single qubit rotation around a Pauli bases. `b` is a Pauli basis, (from the enumeration class for Pauli bases,) `ph` is the single rotation angle "phi," and `q` is the index of the qubit.

**Comment by Zshan0** [comment]
I am done with the first iteration of the sections: standard operations, ALU and logical gates. I have a few queries from these sections as some of them are missing in qrack documentation
- What do `adds` & `subs` do? 
- What is the parameter `o`  in the operation `mul` & `div`? 
- What `muln`, `divn` & `pown` do?
- The functions `lda`, `adc`, `sbc` & `hash` do not have a description in qrack [documentation](https://qrack.readthedocs.io/en/latest/api/qinterface.html) and doxygen seems to give a warning about it on the official website

I'll continue with the other sections once this is clear, thanks :D

**Comment by WrathfulSpatula** [comment]
- "S" indicates "signed" integer arithmetic. For `adds` and `subs`, the `s` parameter is the qubit index that will store the overflow flag. The overflow flag is set when a negative integer added to a negative integer produces a positive integer, or vice versa, or complementary for subtraction. (The native signed arithmetic gate came from the VM6502Q extension to MOS-6502 "classical" 8-bit assembly, but signed arithmetic was one of the only native gates with flag side-effects that added simulator product value in the Python API; "carry" bits can easily be implemented by adding 1 bit to the length of `add` and `sub` operations, with or without a measurement on the carry bit as appropriate, so it didn't make sense to expose "carry" variants as a special case to Python. The "signed integer math" variants are the only ones that are tricky without native support. This just makes _signed_ integer math that much easier, without needing a custom re-implementation, every time.)
- In `mul` and `div`, we need a _carry register_ of _equal_ size to the input qubit register, in general. (Addition and subtraction, with `add` and `sub`, only ever need _one_ carry qubit, but multiplication and division are like a loop-over-addition or loop-over-subtraction, such that the number of extra carry qubits we need, at most, turns out to be the same size as the original input register.)  For _unitary_ multiplication, we can't have an arbitrary modulus on in-place multiplication, because we have always be able to reverse from the output back to the input, or we don't have a _unitary_ operation. (By the way, I have seen simulated quantum multiplication and division implemented _fundamentally incorrectly_ in other places. This is why we have the `o` register parameter: it makes the operation generally _unitary_, or fully "reversible," for "in-place" multiplication)
- `muln`, `divn`, and `pown` are multiply, divide, and raise-to-the-power-of, _modulo `n`_. The point here is that we perform the arithmetic operation for a result we can call "`r`", but then the last step is to replace `r` with `r % n`. This _must_ be an _out-of-place_ operation in general, to be _unitary_. That is, the result must go into a new independent output register that doesn't contain any of the input bits. (These operations are particularly important for Shor's algorithm, by the way.)
- `lda`, `adc`, `sbc` and `hash` are referred to in the underlying Qrack API as `IndexedLDA`, `IndexedADC`, `IndexedSBC`, and `Hash`. The names are borrowed from MOS-6502 assembly: load accumulator, add with carry, subtract with carry, and "hash" is a natural extension of the same general principle to arbitrary one-to-one lookup table transformations. The idea here is that we load a lookup table, with array index for _key_ and array entry value for _value_. These are useful for Grover's search, and they've actually already been used by a student I tutored, in [A Quantum Algorithm To Locate Unknown Hashgrams](https://arxiv.org/abs/2005.02911)

Sorry for the wall of text, but you're getting down into the "juiciest" parts of the API, where the explanations of what operations do might no longer be so simple, without an understanding of classical computer assembly. Keep the questions coming, and thank you again!

**Review by WrathfulSpatula — APPROVED** [review]

**Comment by WrathfulSpatula** [comment]
I'll publish this to the web this weekend, @Zshan0! Thank you so much!

**Pull request merged**
